version: "3.7"

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgre"
    ports:
      - "5432:5432"

volumes:
  postgres: